
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "releve", targetNamespace = "http://releve/", wsdlLocation = "http://localhost:9292/?wsdl")
public class Releve_Service
    extends Service
{

    private final static URL RELEVE_WSDL_LOCATION;
    private final static WebServiceException RELEVE_EXCEPTION;
    private final static QName RELEVE_QNAME = new QName("http://releve/", "releve");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9292/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELEVE_WSDL_LOCATION = url;
        RELEVE_EXCEPTION = e;
    }

    public Releve_Service() {
        super(__getWsdlLocation(), RELEVE_QNAME);
    }

    public Releve_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELEVE_QNAME, features);
    }

    public Releve_Service(URL wsdlLocation) {
        super(wsdlLocation, RELEVE_QNAME);
    }

    public Releve_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELEVE_QNAME, features);
    }

    public Releve_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Releve_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Releve
     */
    @WebEndpoint(name = "RelevePort")
    public Releve getRelevePort() {
        return super.getPort(new QName("http://releve/", "RelevePort"), Releve.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Releve
     */
    @WebEndpoint(name = "RelevePort")
    public Releve getRelevePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://releve/", "RelevePort"), Releve.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELEVE_EXCEPTION!= null) {
            throw RELEVE_EXCEPTION;
        }
        return RELEVE_WSDL_LOCATION;
    }

}
